language: java
sudo: false
jdk:
- oraclejdk8
script:
- cd src
- mvn -N io.takari:maven:wrapper -Dmaven=3.3.3 clean verify
- "./mvnw clean verify"
deploy:
  provider: releases
  api_key:
    secure: eXASwg/We+KHaYsUS7OOWDpCVHc2XNLIjVFzEJ/cmK2ivMoDKJm5zEbD/JtagSEoMUyDdph0rTgT60XXIbvOLfZYKr65VbMkUxQ3TuHPdKz5UEKsfo+0s+Q6YC5CiV0aCEHqWBZ1vSw/ZcP5nRUTJf3dA7DHG6IuXKIGmM2ggvZIAo9DFBmP2hjRRjX7S8bpaEMeZ0PqzVbzmZj3YSfXZBcMzmAAGCK7M9X4y6HuykMDA5QiNYJU5rJnagonK17h9p7WErasi7vkuK6vyHinCbCUUg6HgpLC5bbZQGyMWtxY3DQQrHPBkA8NZ7GHxST12Ppt1Kp3PfBx95ANBW3YbE2AeN8DnN2p0ijvAhinrRUo6s5sw0BkRrI7bU011vVjcjyB8pNfsq449ZCDyzEF27jheacoFyD0d++Zxdc6gJM6UjWpDSM9PHYJoM6wQxK5icrnV3ybUfYiLQORO2hpbId0/MS150W2D2HeSTyo3D27zsDLhR29VQOJ04T0Fa+uGHGsf1/HgcbCJaLs3wPmWo3Nrcr51v8Q25uQLG4CWKAV1dRHk2dCDrVTdG1I0TzY0nlP7Rm4sbl6pnedVA02uDp26fGskU9y8Lk1TvnFOqKTZd7sTKs8KvePm8vmjTFwz4X6OhznzL974HRQV2e4obwsao50SgWImPi4iX50+4w=
  file: src\de.ragedev.example.jaxrs.service.product\target\products\de.ragedev.example.jaxrs.service.product-win32.win32.x86_64.zip
  skip_cleanup: true
  on:
    repo: rage5474/jaxrs-osgi-example
